#!/bin/bash

# CEntos 7 - ten plik powinien znajdować się w /etc/rc.d/init.d/extend

DEVICE="$(df -hkPBG / | tail -1 | awk '{print $1}')"
if [ "$DEVICE" != "/dev/mapper/centos-root" ] && [ "$DEVICE" != "/dev/mapper/VolGroup-lv_root" ]; then
	echo "This is not the standard partitioning scheme."
    echo "Please contact support for further information on extending your disk space."
	echo "Exiting..."
    exit 1
fi

extendfs() {

cat <<EOF >> /etc/rc.d/init.d/extendfs
#!/bin/bash

## Resize filesystem on /dev/sda2
echo "pvresize /dev/xvda2" >> /var/log/vm_resize.log
pvresize /dev/xvda2 &>> /var/log/vm_resize.log
echo "lvresize -l +100%FREE /dev/mapper/centos/root" >> /var/log/vm_resize.log
lvresize -l +100%FREE /dev/mapper/centos/root &>> /var/log/vm_resize.log
echo "xfs_growfs /dev/mapper/centos-root" >> /var/log/vm_resize.log
xfs_growfs /dev/mapper/centos-root &>> /var/log/vm_resize.log
rm /etc/rc.d/init.d/extendfs

EOF
chmod +x /etc/rc.d/init.d/extendfs
}

echo "Starting disk resize..."
echo "User initiated VM disk resize" >> /var/log/vm_resize.log	
extendfs
echo -e "d\n2\nn\np\n2\n\n+\nt\n2\n8e\nw" | fdisk /dev/xvda &>> /var/log/vm_resize.log
rm -f /etc/rc.d/init.d/extend
echo "Rebooting to finish install"
shutdown -r now
