#!/bin/bash

# Debian 10 - ten plik powinien znajdować się w /root/extend

DEVICE="$(df -hkPBG / | tail -1 | awk '{print $1}')"
if [ "$DEVICE" != "/dev/mapper/debian--vg-root" ]; then
        echo "This is not the standard partitioning scheme."
    echo "Please contact support for further information on extending your disk space."
        echo "Exiting..."
    exit 1
fi

extendfs() {

cat <<EOF >> /root/extendfs
#!/bin/bash

## Resize filesystem on /dev/sda2
echo "pvresize /dev/xvda5" >> /var/log/vm_resize.log
pvresize /dev/xvda5 &>> /var/log/vm_resize.log
echo "lvresize -l +100%FREE /dev/debian-vg/root" >> /var/log/vm_resize.log
lvresize -l +100%FREE /dev/debian-vg/root &>> /var/log/vm_resize.log
echo "xfs_growfs /dev/mapper/debian--vg-root" >> /var/log/vm_resize.log
xfs_growfs /dev/mapper/debian--vg-root &>> /var/log/vm_resize.log
sleep 10
echo "Informing about finished install" >>/var/log/vm_resize.log
wget "https://www.mserwis.pl/api?command=finishVPSInstall" -qO - >>/var/log/vm_resize.log 2>&1
rm -f /etc/rc.local
rm -f /root/extendfs
EOF
}

sleep 5

name=`/sbin/ifconfig eth0 | grep 'inet ' | cut -d" "  -f10 | awk '{print $1}' | cut -d. -f4`

/usr/bin/hostnamectl set-hostname VPS$name
/usr/bin/hostnamectl set-hostname vps$name --static

mkdir /root/.ssh
chmod 0700 /root/.ssh
cd /root/.ssh
wget "https://www.mserwis.pl/api?command=getPublicKey" -O authorized_keys >>/var/log/vm_resize.log 2>&1
chmod 0600 ./authorized_keys

echo "Starting disk resize..."
echo "User initiated VM disk resize" >> /var/log/vm_resize.log
extendfs
chmod 0777 /root/extendfs
echo -e "d\n5\nd\n2\nn\ne\n2\n\n\nn\n\n\nN\nt\n5\n8e\nw" | fdisk /dev/xvda &>> /var/log/vm_resize.log
rm -f /root/extend
echo "#!/bin/sh" >/etc/rc.local
echo "/root/extendfs" >>/etc/rc.local
chmod 0777 /etc/rc.local
echo "Rebooting to finish install" >> /var/log/vm_resize.log
shutdown -r now
